### ISSUE TITLE
On Windows, can't delete PDF while it's open in Score View

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#1]
```
What steps will reproduce the problem?
Edit and save the source the score of which is displayed in the Score View, or 
just try to delete that score.

What is the expected output? What do you see instead?
The score can't be deleted because it's locked by Windows so the 
compilation/deletion fails.

Version: 0.1.0.201007010147
```

Original issue reported on code.google.com by `harmathdenes` on 1 Jul 2010 at 12:14

**Comment by nittka** [comment]
Proposed patch to PdfViewPage in org.eclipse.ui.views.pdf. Add the following after line 439 at the end of the creatHyperlinksJob-Run method...

if(pdfDecoder!=null && pdfDecoder.isOpen()){
pdfDecoder.closePdfFile();
}

**Comment by thSoft** [comment]
Unfortunately, this modification breaks source -> score hyperlinks.

**Comment by nittka** [comment]
I see. Too bad that registering a resource change listener did not work either. The notification is not sent before deletion is attempted (only after deletion successful deletion), otherwise the pdfDecoder.closePdfFile could have been called based on such an event. Given time, I will do some further investigation.

**Comment by nittka** [comment]
I've had a look at the LilyPondHyperlinkHelper. Can you tell me why the pdfViewPage has to be asked for the pageCount in order to iterate over annotations for each page separately? The annotations are all stored in the pdfViewPage, anyway, so a simple getAllAnnotations method returning a flattened list will yield the same result without having to involve the pdfDecoder.
I have tried locally and with that modification linking seems to work as before.

This is not saying that the above modification closing the pdf file has no other side effects.
