### ISSUE TITLE
Compilation cancelling doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#48]
```
Cancelling a compilation process has no effect. This is particulary bad when 
recompiling a file quickly twice in a row, as there can be a file writing 
conflict between the two processes.
```

Original issue reported on code.google.com by `harmathdenes` on 3 Aug 2012 at 9:38

**Comment by nittka** [comment]
There are two main reasons why the current implementation of CompilerJob does no cancelling.
1. the run method makes no use of the monitor which provides information about the cancel status
2. The ProcessBuilder class does not seem to provide any hook for cancelling and ProcessUtils.runProcess returns the process only after it is finished.

A second thread checking the monitor and destroying the process (rather than CompilerJob#canceling which kicks in too late) might be an option.

**Comment by thSoft** [comment]
@nittka May I please ask you to also implement a UI button on the Console view? Then this issue would be completed.

**Comment by nittka** [comment]
@thSoft I can try, cannot make promises on the time line, though.

**Comment by thSoft** [comment]
:D Don't worry, I have not established any deadlines. However, I would like to perform a release some time before Mars.
