### ISSUE TITLE
Moving a source file and its compiled file causes "File not found"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#53]
```
If you move a source file simultaneously with a file compiled from it, the 
refactoring will fail with "File not found" error and the move participant will 
be disabled.
```

Original issue reported on code.google.com by `harmathdenes` on 9 Aug 2012 at 1:39

**Comment by nittka** [comment]
I disabled line 56 in MoveFileParticipant (result.addFatalError("Moving a LilyPond source file and a file compiled from it is not supported");) in order to be able to move a source file along with the generated pdf. However, I cannot reproduce the error described on a Windows machine. Moving both files works for me.

**Comment by thSoft** [comment]
On Windows 8.1, if I remove this check, I get no error when moving the source and the corresponding score file; however I encountered another issue: #72.
