### ISSUE TITLE
On Windows, moving a PDF file copies it

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#72]
On Windows 8.1, moving a PDF file leaves a copy in the original location.

**Comment by nittka** [comment]
I am not so sure anymore if #53 is really solved (for good). It is possible that the Elysium MoveParticipant is disabled because deleting the pdf file (i.e. moving it) causes an exception.

What I wanted to try (given time, very likely not before next week) is adding a MoveParticipant just like the DeleteParticipant to the pdf view (debugging indicated that it is not called when trying to move source and pdf).

**Comment by nittka** [comment]
I hope this issue is solved with the two pull requests on commons and elysium

**Comment by thSoft** [comment]
Fixed by merging #73 and thSoft/eclipse-commons#3
