### ISSUE TITLE
Integration test doesn't find non-built-in included files

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#87]
There are `Imported resource could not be found.` errors on `\include`s when validating the real-world integration test files.

**Comment by nittka** [comment]
Without looking into the code, I guess the problem is as follows. The test reads the file from the file system but simply parses a string. So the include mechanism has no chance of locating the included file relative to the including file. It would be worth checking whether reading the model specifying the correct file URI of the file to test already solves the problem.

**Comment by thSoft** [comment]
Fixed by #88
